-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 11:34:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jr_course
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jr_course` ;

-- -----------------------------------------------------
-- Schema jr_course
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jr_course` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jr_course` ;

-- -----------------------------------------------------
-- Table `jr_course`.`grammar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`grammar` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`grammar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` INT NOT NULL DEFAULT '5',
  `formula` VARCHAR(45) NOT NULL,
  `example` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jr_course`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`user` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jr_course`.`grammar_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`grammar_user` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`grammar_user` (
  `grammar_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`grammar_id`, `user_id`),
  INDEX `fk_grammar_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_grammar`
    FOREIGN KEY (`grammar_id`)
    REFERENCES `jr_course`.`grammar` (`id`),
  CONSTRAINT `fk_grammar_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `jr_course`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jr_course`.`word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`word` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`word` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NOT NULL DEFAULT 'easy',
  `jp_kanji` VARCHAR(45) NULL DEFAULT NULL,
  `jp_kana` VARCHAR(45) NOT NULL,
  `ru_word` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jr_course`.`word_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`word_user` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`word_user` (
  `word_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`word_id`, `user_id`),
  INDEX `fk_word_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_word`
    FOREIGN KEY (`word_id`)
    REFERENCES `jr_course`.`word` (`id`),
  CONSTRAINT `fk_word_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `jr_course`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jr_course`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`note` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_note_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jr_course`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jr_course`.`exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jr_course`.`exercise` ;

CREATE TABLE IF NOT EXISTS `jr_course`.`exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `task` MEDIUMTEXT NOT NULL,
  `answer` MEDIUMTEXT NOT NULL,
  `grammar_id` INT NOT NULL,
  PRIMARY KEY (`id`, `grammar_id`),
  INDEX `fk_exercise_grammar1_idx` (`grammar_id` ASC) VISIBLE,
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_grammar1`
    FOREIGN KEY (`grammar_id`)
    REFERENCES `jr_course`.`grammar` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
